### ISSUE TITLE
Redirect to My NFTs once bought

### ISSUE THREAD

**Issue by jafri** [ProtonProtocol/nft-demo#25]
Once the user buys a NFT, lets redirect them to their My NFTs, which will work great with #27

**Comment by joesobo** [comment]
Changing to redirect to the bought asset page as it should be more useful for the user

**Comment by jafri** [comment]
Fred already decided it should go to My NFTs

Sent from my iPhone

On Mar 22, 2021, at 11:09 AM, Joe Soboleski ***@***.***> wrote:

﻿
[△EXTERNAL]



Changing to redirect to the bought asset page as it should be more useful for the user
