### ISSUE TITLE
Rething serial sorting (e.g. by price)

### ISSUE THREAD

**Issue by cryptotester** [ProtonProtocol/nft-demo#31]
Hi, when checking the details of an NFT, please rethink the serial number dropdown. Allow to sort NFTs by ID or price, ascending or descending.

Now the order looks like random, see screenshot:

![image](https://user-images.githubusercontent.com/49552918/111988703-1c463480-8b11-11eb-82d0-53369b13373f.png)

Also what happens if the dropdown has thousands of articles for sale?

**Comment by joannerd** [comment]
Hi, thanks for posting! Closing this issue since it was resolved in PR #33 which was just merged in an hour ago.
