### ISSUE TITLE
Wrong lowest price

### ISSUE THREAD

**Issue by cryptotester** [ProtonProtocol/nft-demo#41]
Dullahan shows up at 2 FOOBAR, but when I click it the lowest price is actually 2 millions. See also other NFTs.
Browser: Brave.

I think you messed up something if price is too high you divide by 1000?
Also if I try to buy it it doesn't stop me, it actually starts the transaction that I must confirm on my wallet, just to see that I don't have balance. It should prevent it directly if the balance is not enough (the marketplace knows my balance as I have to deposit before buying, so somewhere the price is really messed up).

![image](https://user-images.githubusercontent.com/49552918/112102779-0edc8900-8ba9-11eb-93da-366fe2b95867.png)

![image](https://user-images.githubusercontent.com/49552918/112102812-1ef46880-8ba9-11eb-9bc9-863dbbc47971.png)

**Comment by joannerd** [comment]
Thanks for posting this! We just merged in a PR with a fix for this issue. We realized that if a number like "12,000" is fed into the default JavaScript "parseFloat" function, the output is actually "12" instead of the expected "12000".
