### ISSUE TITLE
My NFTs - group doubles (like in the marketplace)

### ISSUE THREAD

**Issue by cryptotester** [ProtonProtocol/nft-demo#42]
My NFTs page looks like this because I bought the same NFTs a few times, some to collect, some to sell later a bit higher and make some profits (kinda a realistic use case):

![image](https://user-images.githubusercontent.com/49552918/112151361-6bf43100-8be1-11eb-8824-d15490295dcd.png)

It would be nice to group the same NFTs under the same image. Then either when clicking I'd see a detail page like now, or a page showing all the editions.

I'm no UX expert but I think a good solution could be to show a dropdown in the "My NFTs page" under each NFT, when the owned ID is clicked the detail page of that particular one would open the asset page, like now. If there is only one NFT show just a text, if more are owned of the same show the dropdown. It may look not so nice if there is only one with a dropdown and the others are unique. Must be tested a bit, maybe you find a nice looking "+" button to expand or something like that...

**Comment by joannerd** [comment]
Great idea! I believe we have something like this in the works, but designs are being finalized. We'll connect the PR with this UI improvement to this issue to keep you posted.

**Comment by cryptotester** [comment]
May I add also to improve this page in general, like add sorting by:
- rarity (e.g. 100s edition comes before 200s etc.)
- name
- purchase price
- purchase datetime
- actual lowest value (compare the same item being sold and show its minimum price in the market, and show the price too, so you know how much it's worth the cheapest one now)
- other sorting...

Feel free to create a new issue if you think this is a new feature. But since you said you have some new designs in progress maybe you wanted to improve this page already and this could be related too.

**Comment by cryptotester** [comment]
Thank you for fixing the template, now it looks really nicer:

![image](https://user-images.githubusercontent.com/49552918/112796386-31b7e300-906a-11eb-8ffd-2d5fe523f46d.png)

Closing this issue as I see you opened issue #65 containing the additional suggestions.
