### ISSUE TITLE
Bug: my-nft page broken with template_ids from other collections

### ISSUE THREAD

**Issue by cryptotester** [ProtonProtocol/nft-demo#90]
Hi, don't have time to make a PR, so here the fix:

To reproduce the error, check this out:

https://nft.protonchain.com/my-nfts/cryptotester

Here the fix:

File: `services/templates.ts:`

Replace:

```
    const templateIds = accountResponse.data.templates
      .map(({ template_id }) => template_id)
      .splice((page - 1) * 10, 10);
```

With:

```
    const templateIds = accountResponse.data.templates
      .filter((tpl) => tpl.collection_name === DEFAULT_COLLECTION)
      .map(({ template_id }) => template_id)
      .splice((page - 1) * 10, 10);
```

Like this you filter just templates of the monsters collection ;)

Cheers

**Comment by goattude** [comment]
I am having the same issue that cryptotester is experiencing.

**Comment by cryptotester** [comment]
Every customer of my NFT marketplace (or people minting their own NFTs) will experience the same bug. Because without the filter as I added in my fix, the response will contain also other template_ids not compatible with the ones of the demo...
